version: '3.8'

services:

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
          - "5434:5432"
    container_name: postgres_db_track_todo_app

  app:
    build: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: app:django
    container_name: django_track_todo_app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db