# Generated by Django 3.2.13 on 2023-04-29 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
        ('todo', '0002_notify'),
    ]

    operations = [
        migrations.AddField(
            model_name='notify',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask'),
        ),
        migrations.AddField(
            model_name='notify',
            name='title',
            field=models.CharField(default='Notify my tasks', max_length=255),
        ),
        migrations.AlterField(
            model_name='notify',
            name='day_of_week',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='notify',
            name='hour',
            field=models.CharField(default='7', max_length=20),
        ),
        migrations.AlterField(
            model_name='notify',
            name='minute',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
